### ISSUE TITLE
clean data

### ISSUE THREAD

**Issue by matthieuMoisson** [JoymangulJensen/dataVIz-human-migration#1]
@tblondelle  can you sort all the table migration_2000_2015.csv by codecountry? i see you begin script in python. But if you do just that it's great.
I use 'migration_2000_2015.csv' in the web page. It's working but i need to have sorted data... If you can't tell me i can try.

**Comment by matthieuMoisson** [comment]
@JoymangulJensen  As you can see my english is very good ;). We do all in english so i speak in english too... ^^

**Comment by JoymangulJensen** [comment]
I'm pretty impress by your english. Such performance must be cheers 🥂  👏!! Lol

**Comment by matthieuMoisson** [comment]
I thought the only solution to have my toiec is to speak all time in english. It's my new resolution for 2018. Maybe i will change quicly

**Comment by JoymangulJensen** [comment]
Man, I think it's too good to be true hahaha. I rather believe in Santa than in your new resolution. Just kidding for sure it will help yr english 😉😉

**Comment by tblondelle** [comment]
Not an issue at all pal! I'll do that tomorrow (adding an column of country code for each column of country)

**Comment by tblondelle** [comment]
That was mostly a problem of "two many files in a folder": I have done some cleaning in it. Tell me if the file "/data/migration_data.csv" is alright for you. The first lines are:
> focus,country,year,nbFromCountryToFocus
> AUS,AFG,2000,887
> AUS,AFG,2001,456
> AUS,AFG,2002,660
> AUS,AFG,2003,1015
> AUS,AFG,2004,1340
> AUS,AFG,2005,3463
> ...

**Comment by matthieuMoisson** [comment]
Be careful when you clean the folder. I use file in this folder on the web page... When you change the name it make an error. And change name of col too : 
![image](https://user-images.githubusercontent.com/15812541/34326136-4cc05b24-e8a6-11e7-872d-408b3c9a77cd.png)


Futhermore the file migration_data.csv is not good for me. I juste need the old file sort by the first column. Keep all the column and just sort by the first one (codecountry).
![image](https://user-images.githubusercontent.com/15812541/34326173-ebc77c16-e8a6-11e7-891a-3be33276fc8b.png)

I give you on gmail my phone number. Tel me if you don't understand my bad english 🥇
