### ISSUE TITLE
Legend Outflow and Inflow sizes and values

### ISSUE THREAD

**Issue by tblondelle** [JoymangulJensen/dataVIz-human-migration#11]

**Comment by matthieuMoisson** [comment]
I don't understand this?

**Comment by tblondelle** [comment]
C'est juste que la légende ne donne pas les bonnes valeurs, enfin je
crois...

Le 3 janv. 2018 20:28, "Matthieu MOISSON" <notifications@github.com> a
écrit :

**Comment by matthieuMoisson** [comment]
J'ai mis la même formule pourtant... c'est une somme des année sélectionne. Donc certain  pays on vraiment beaucoup d'autre moins. C'est pour sa que j'ai fait racine.... Après afficher une bulle quand on survolle serai un plus...

**Comment by tblondelle** [comment]
Ça marche ! J'avoue ne pas avoir regarde en détail... Les petites bulles
sont une bonne idée mais il ne faudrait pas que ça interfère avec les
bulles des pays... Je vais travailler dessus demain. Pour les centroïdes,
ça me paraît difficile d'avoir une solution simple ou élégante... On peut
laisser comme ça pour le moment.

Le 3 janv. 2018 22:39, "Matthieu MOISSON" <notifications@github.com> a
écrit :

**Comment by matthieuMoisson** [comment]
Si tu arrive à le mettre en place je ne pense pas que sa gênera de trop. En plus on peut choisir le nombre de arcs. Sa serai complet. Après j'ai pas réussi mais j'ai pas insister.
Pour centroid on pourra justement en parler que c'est une issu qu'on a laissé car compliqué. C'est un problème vue mais j'ai pas trouvé de solution.
