### ISSUE TITLE
comming from and going to is reverse

### ISSUE THREAD

**Issue by matthieuMoisson** [JoymangulJensen/dataVIz-human-migration#14]

**Comment by tblondelle** [comment]
Non : je me suis basé sur le nombre de Mexicains qui vont aux USA et ceux
qui en reviennent pour attribuer les coming et going.

Le 5 janv. 2018 14:04, "Matthieu MOISSON" <notifications@github.com> a
écrit :

**Comment by matthieuMoisson** [comment]
Je regarderai de plus proche. C'est peut être les fleches qui ne sont pas bonnes aussi? Je regarderai sa.
Sinon la vizualisation est vraiment pas mal je trouve =).

**Comment by matthieuMoisson** [comment]
![image](https://user-images.githubusercontent.com/15812541/34613322-a4fdb9d6-f22d-11e7-8c91-8e6f14f0d560.png)

**Comment by matthieuMoisson** [comment]
Je pense que c'est plutot : 
going to Canada nan
comming from canada 3158

**Comment by tblondelle** [comment]
Normalement, c'est bien le contraire : comme la Russie n'est pas membre de l'OCDE, on n'a pas les données pour le nombre de Canadiens qui vont en Russie (La Russie ne leur a pas donné les données). Par contre, le Canada partage toutes les données des immigrants, et notamment le nombre de Russes qui viennent chez eux.

**Comment by matthieuMoisson** [comment]
Alors je pense que j'ai fait une bétise avec les flêches. Pour moi vert c'est ce qui arrive dans le pays et rouge ce qui part...

**Comment by matthieuMoisson** [comment]
Dans ma logique...

**Comment by tblondelle** [comment]
Du coup, j'avais interprété le contraire (vert, c'est ceux qui part et rouge, ceux qui rentrent) !
