### ISSUE TITLE
create a slider interval

### ISSUE THREAD

**Issue by matthieuMoisson** [JoymangulJensen/dataVIz-human-migration#2]
search any solution to create a beautiful slider with two selector.
@JoymangulJensen @tblondelle

**Comment by tblondelle** [comment]
I'm on it.

**Comment by tblondelle** [comment]
That (http://jqueryui.com/slider/#range) seems enough !

**Comment by tblondelle** [comment]
I have adapted this solution for it: https://bl.ocks.org/linoba/ecfc96ae52d5f8b8a7435ee5ab49635a. (The interaction jQuery/d3.js is not yet perfect)
