### ISSUE TITLE
draw the arrow when ou clic on a selected country. and color the map with the pib

### ISSUE THREAD

**Issue by matthieuMoisson** [JoymangulJensen/dataVIz-human-migration#4]

**Comment by tblondelle** [comment]
I have provided a temporary solution:
1. At the beginning, you see nothing
2. If you click on PIB, the colors in the map change accordingly to the selected range.
3. If you click on Migrant-ratio, the colors in the map change accordingly to the selected range.
4. If you click on a country, the colors in the map change accordingly to the selected range.
5. If you click on reset, you see nothing.

Changing the range won't update the map: you have to click again on a button or in the map to see the changes.
