### ISSUE TITLE
Data migration. 

### ISSUE THREAD

**Issue by matthieuMoisson** [JoymangulJensen/dataVIz-human-migration#5]
I have a probleme. I am not sur but i think some data is missing. 
Can we try to just clean the original file (migration_data_2000_2015_untouched.csv) who have more than 300 000 line? And sort like the last one. Just keep CO2, Country, Value, Year.

**Comment by matthieuMoisson** [comment]
Can you see to do that @tblondelle ? If you can't or don't understant ask me.

**Comment by matthieuMoisson** [comment]
Maibe they has two probleme : 
- First one they missed some data. Missing on the initial data or after convert? (what about "Stock of foreign-born population by country of birth" for example). Maybe they missed on the initial data.
- In the web page i forget that AUS,INFLOW,AFG == AFG,INFLOW,AUS but juste one of then or in the data. 

Can we call Tuesday to speak about?

**Comment by matthieuMoisson** [comment]
Je pense avoir résolu une partie du probleme qui venais de moi. 
Pour moi je ne sais juste pas ce qu'on fait des donnée "Stock of foreign-born population by country of birth" ? des données initial? @tblondelle

**Comment by tblondelle** [comment]
Ces données là, on s'en moque : c'est une description statique de la population d'un pays. Nous, nous voulons les flux de population, les mouvements.

**Comment by tblondelle** [comment]
Oui, on peut en parler mardi !
