### ISSUE TITLE
When mouseover arrow we can display information like the exact number of migrant? I try but i don't know why i can't...

### ISSUE THREAD

**Issue by matthieuMoisson** [JoymangulJensen/dataVIz-human-migration#8]

**Comment by tblondelle** [comment]
Do you want the exact number like `Inflow: 12356789` instead of `Inflow: 12,56 M` ?

**Comment by matthieuMoisson** [comment]
The number like you want.... It's just this information so yo can put 12356789. If you can 12 356 987 can be better?
