### ISSUE TITLE
Stroke size of arrows

### ISSUE THREAD

**Issue by tblondelle** [JoymangulJensen/dataVIz-human-migration#9]
They are not always visible (click on USA for instance). 
Some possible solutions:

- limit the number of arrows (max= 20) for the most important flux.
- change the color or the opacity in relation with the importance of the flux

**Comment by matthieuMoisson** [comment]
Maybe it's the same solution.  The second solution will just disappear the less important flux.

Limit number of arrow it's good idear. We can also offer the possibility to change this limit? Not change the code a lot...
